import React, { useEffect, useState } from 'react'
import { Card, FormField, Loader } from '../components'


const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />)
  }

  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  )
}

const Community = () => {

  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)

  const [searchText, setSearchText] = useState('')
  const [searchedResults, setSearchedResults] = useState(null)
  const [searchTimeout, setSearchTimeout] = useState(null)

  const fetchPosts = async () => {
    setLoading(true);
    try {
      const res = await fetch('https://imagenation-api.vercel.app/api/v1/posts', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json'
        },
      });

      if (res.ok) {
        const result = await res.json();
        console.log(result.data)
        setAllPosts(result.data.reverse());
      }
    } catch (error) {
      console.log(error)
    } finally {
      setLoading(false)
    }
  }

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()) || item.name.toLowerCase().includes(searchText.toLowerCase()));

        setSearchedResults(searchResult);
      }, 500)
    );
  }

  useEffect(() => {
    fetchPosts();
  }, [])

  return (
    <section className='p-5 flex flex-col justify-center items-center bg-cyan-400 min-h-screen dark:bg-slate-800'>
      <div>

      </div>

      <div className='flex flex-col justify-center items-center text-center'>
        <h1 className='font-extrabold text-[#222328] text-[32px] dark:text-cyan-400'>The community</h1>
        <p className='mt-2 text-black text-[20px] max-w-[500px] dark:text-white'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className='mt-16'>
        <FormField
          labelName="Search Posts"
          type="text"
          name="text"
          placeholder="Search Posts"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className='mt-10 flex flex-col'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-[#666e75] text-xl mb-3'>Showing Results for <span className='text-[#222328]'>{searchText}</span> </h2>
            )}
            <div className='grid lg:grid-cols-3 sm:grid-cols-3 xs:grid-cols-2 items-center'>
              {searchText ? (
                <RenderCards data={searchedResults} title='No search results found !'
                />
              ) : (
                <>
                  <RenderCards data={allPosts} title='No posts found !'
                  />
                </>
              )}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Community